
service: badeball-api

provider:
  name: aws
  runtime: python3.7
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ok-origo-dataplatform-config-${self:provider.stage}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  iamManagedPolicies:
    - { 'Fn::Join': [':', ['arn:aws:iam:', { Ref: 'AWS::AccountId' }, 'policy/badeball-api-policy']] }

functions:
  getAllTemperatures: ${file(serverless/functions/getAllTemperatures.yml)}

package:
  exclude:
    - "**/*"
  include:
    - "src/main/*.py"
    - "serverless/documentation/schemas/*.json"

plugins:
  - serverless-python-requirements
  - serverless-aws-documentation
custom:
  pythonRequirements:
    dockerizePip: non-linux
  #documentation: ${file(serverless/documentation/documentation.yaml)}