frameworkVersion: ">=2.10.0 <3.0.0"

service: badetemperatur-api

provider:
  name: aws
  runtime: python3.7
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ok-origo-dataplatform-config-${self:provider.stage}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  rolePermissionsBoundary: "arn:aws:iam::#{AWS::AccountId}:policy/oslokommune/oslokommune-boundary"
  iamManagedPolicies:
    - arn:aws:iam::#{AWS::AccountId}:policy/badetemperatur-api-policy
  tags:
    GIT_REV: ${git:branch}:${git:sha1}
  environment:
    GIT_REV: ${git:branch}:${git:sha1}
    ENV: ${opt:stage, 'dev'}

functions:
  getAllTemperatures: ${file(serverless/functions/getTemperatures.yml)}
  write_latest_measurement: ${file(serverless/functions/writeLatestMeasurement.yml)}

package:
  exclude:
    - "**/*"
  include:
    - "badetemperatur_api/*.py"
    - "serverless/documentation/schemas/*.json"

plugins:
  - serverless-python-requirements
  - serverless-aws-documentation
  - serverless-pseudo-parameters
  - serverless-plugin-git-variables

custom:
  pythonRequirements:
    dockerizePip: non-linux
    usePoetry: false
  documentation: ${file(serverless/documentation/documentation.yml)}
