openapi: "3.0.1"
info:
  title: "dev-badeball-api"
  description: "Api for extracting data from water temperature sensors in Oslo."
  contact:
    name: "Origo Dataplatform team"
    email: "dataplattform@oslo.kommune.no"
  version: "2019-04-16T08:53:28Z"
servers:
- url: "https://***REMOVED***.execute-api.eu-west-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/dev"
paths:
  /temperatures/{name}:
    get:
      description: "Returns temperature measurement objects for a single sensor."
      parameters:
      - name: "name"
        in: "path"
        description: "Identifier for sensor."
        required: true
        schema:
          type: "string"
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MeasurementObject"
  /temperatures:
    get:
      description: "Returns temperature measurement objects for sensors."
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MeasurementObjectList"
components:
  schemas:
    Temperature:
      type: "object"
      properties:
        unit:
          type: "string"
        value:
          type: "number"
          format: "float"
      description: "Temperature measurement"
    MeasurementObject:
      type: "object"
      properties:
        airTemperature:
          $ref: "#/components/schemas/Temperature"
        name:
          type: "string"
        waterTemperature:
          $ref: "#/components/schemas/Temperature"
        location:
          $ref: "#/components/schemas/Location"
        measureTime:
          type: "string"
          format: "date-time"
      description: "Measurement from a single sensor."
    Location:
      type: "object"
      properties:
        latitude:
          type: "number"
          format: "float"
        name:
          type: "string"
        id:
          type: "string"
        longitude:
          type: "number"
          format: "float"
      description: "Location"
    MeasurementObjectList:
      type: "array"
      description: "Measurements from all sensors."
      items:
        $ref: "#/components/schemas/MeasurementObject"
