openapi: "3.0.1"
info:
  title: "dev-badeball-api"
  description: "Api for extracting data from water temperature sensors in Oslo."
  contact:
    name: "Origo Dataplatform team"
    email: "dataplattform@oslo.kommune.no"
  version: "2019-04-23T12:20:15Z"
servers:
- url: "https://***REMOVED***.execute-api.eu-west-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/dev"
paths:
  /temperatures/{location}:
    get:
      description: "Returns last recorded temperature measurement for a single location."
      parameters:
      - name: "location"
        in: "path"
        description: "Identifier for location."
        required: true
        schema:
          type: "string"
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Measurement"
  /temperatures:
    get:
      description: "Returns last recorded temperature measurement for a all locations."
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Measurements"
components:
  schemas:
    Measurement:
      type: "object"
      properties:
        name:
          type: "string"
        temperature:
          $ref: "#/components/schemas/Temperature"
        location:
          $ref: "#/components/schemas/Location"
        measureTime:
          type: "string"
          format: "date-time"
      description: "Measurement from a single location."
    Temperature:
      type: "object"
      properties:
        unit:
          type: "string"
        value:
          type: "number"
          format: "float"
      description: "Temperature measurement"
    Measurements:
      type: "array"
      description: "Measurements from all locations."
      items:
        $ref: "#/components/schemas/Measurement"
    Location:
      type: "object"
      properties:
        latitude:
          type: "number"
          format: "float"
        name:
          type: "string"
        id:
          type: "string"
        longitude:
          type: "number"
          format: "float"
      description: "Location"
