openapi: "3.0.1"
info:
  title: "dev-badetemperatur-api"
  description: "Api for extracting data from water temperature sensors in Oslo."
  contact:
    name: "Origo Dataplatform team"
    email: "dataplattform@oslo.kommune.no"
  version: "2019-05-20T15:06:25Z"
servers:
- url: "https://***REMOVED***.execute-api.eu-west-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/dev"
paths:
  /temperatures:
    get:
      description: "Returns last recorded temperature measurement for all locations. Offers query parameter for filtering locations."
      parameters:
      - name: "location"
        in: "query"
        description: "Identifier for location"
        schema:
          type: "string"
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Measurements"
components:
  schemas:
    Measurement:
      required:
      - "location"
      - "measureTime"
      - "temperature"
      type: "object"
      properties:
        name:
          type: "string"
        temperature:
          $ref: "#/components/schemas/Temperature"
        location:
          $ref: "#/components/schemas/Location"
        measureTime:
          type: "string"
          format: "date-time"
        sensorId:
          type: "string"
      additionalProperties: false
      description: "Measurement from a single location."
    Temperature:
      required:
      - "unit"
      - "value"
      type: "object"
      properties:
        unit:
          type: "string"
        value:
          type: "number"
          format: "float"
      additionalProperties: false
      description: "Temperature measurement"
    Measurements:
      type: "array"
      description: "Measurements from all locations."
      items:
        $ref: "#/components/schemas/Measurement"
    Location:
      required:
      - "id"
      type: "object"
      properties:
        latitude:
          type: "number"
          format: "float"
        name:
          type: "string"
        id:
          type: "string"
        longitude:
          type: "number"
          format: "float"
      additionalProperties: false
      description: "Location"
